# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

staples = Category.create(title: 'Staples')
staples.children.create(title: 'Maize')
staples.children.create(title: 'Millet')
staples.children.create(title: 'Sorghum')
staples.children.create(title: 'Rice')
staples.children.create(title: 'Wheat')
staples.children.create(title: 'Cassava')
staples.children.create(title: 'Yam')
staples.children.create(title: 'Cocoyam')
staples.children.create(title: 'Sweet Potato')
staples.children.create(title: 'Potato')
staples.children.create(title: 'Plantain')

nuts_and_seeds = Category.create(title: 'Nuts and Seeds')
nuts_and_seeds.children.create(title: 'Groundnut (Peanut)')
nuts_and_seeds.children.create(title: 'Soya Beans')
nuts_and_seeds.children.create(title: 'Chili Peppers')
nuts_and_seeds.children.create(title: 'Sesame')
nuts_and_seeds.children.create(title: 'Green Corn')
nuts_and_seeds.children.create(title: 'Coconut')
nuts_and_seeds.children.create(title: 'Kola Nut')
nuts_and_seeds.children.create(title: 'Cashew Nut')
nuts_and_seeds.children.create(title: 'Tobacco Leaves')
nuts_and_seeds.children.create(title: 'Sunflower Seeds')
nuts_and_seeds.children.create(title: 'Rapeseed')
nuts_and_seeds.children.create(title: 'Bitter Kola')
nuts_and_seeds.children.create(title: 'Garcinia Kola')
nuts_and_seeds.children.create(title: 'Canola')
nuts_and_seeds.children.create(title: 'Sunflower Seeds')
nuts_and_seeds.children.create(title: 'Walnuts')
nuts_and_seeds.children.create(title: 'Dried Hibiscus Flower')
nuts_and_seeds.children.create(title: 'Banana')

cash_crops = Category.create(title: 'Cash Crops')
cash_crops.children.create(title: 'Oil Palm Fruit')
cash_crops.children.create(title: 'Palm Kernels')
cash_crops.children.create(title: 'Palm Oil')
cash_crops.children.create(title: 'Palm Kernel Shell')
cash_crops.children.create(title: 'Coffee Beans')
cash_crops.children.create(title: 'Seed Cotton')
cash_crops.children.create(title: 'Cotton Lint')
cash_crops.children.create(title: 'Cotton Seed')
cash_crops.children.create(title: 'Cocoa Beans')
cash_crops.children.create(title: 'Rubber')
cash_crops.children.create(title: 'Sugar Cane')

vegetables_and_fruits = Category.create(title: 'Vegetables and Fruits')
vegetables_and_fruits.children.create(title: 'Carrot')
vegetables_and_fruits.children.create(title: 'Cucumber')
vegetables_and_fruits.children.create(title: 'Melon (Egusi)')
vegetables_and_fruits.children.create(title: 'Papaya (PawPaw)')
vegetables_and_fruits.children.create(title: 'Okra')
vegetables_and_fruits.children.create(title: 'Mangoes')
vegetables_and_fruits.children.create(title: 'Pineapples')
vegetables_and_fruits.children.create(title: 'Onions')
vegetables_and_fruits.children.create(title: 'Tomatoes')
vegetables_and_fruits.children.create(title: 'Ginger')
vegetables_and_fruits.children.create(title: 'Garlic')

farm_fisheries = Category.create(title: 'Farm Fisheries')
farm_fisheries.children.create(title: 'Tilapia')
farm_fisheries.children.create(title: 'Catfish')
farm_fisheries.children.create(title: 'Shrimps')
farm_fisheries.children.create(title: 'Snail')

livestock_and_byproducts = Category.create(title: 'Livestock & Byproducts')
livestock_and_byproducts.children.create(title: 'Cattle')
livestock_and_byproducts.children.create(title: 'Goats')
livestock_and_byproducts.children.create(title: 'Sheep')
livestock_and_byproducts.children.create(title: 'Asses')
livestock_and_byproducts.children.create(title: 'Horses')
livestock_and_byproducts.children.create(title: 'Camels')
livestock_and_byproducts.children.create(title: 'Cow Milk')
livestock_and_byproducts.children.create(title: 'Goat Milk')
livestock_and_byproducts.children.create(title: 'Pig')

poultry = Category.create(title: 'Poultry')
poultry.children.create(title: 'Chicken')
poultry.children.create(title: 'Chicken Eggs')
poultry.children.create(title: 'Duck')
poultry.children.create(title: 'Duck Eggs')
poultry.children.create(title: 'Goose')
poultry.children.create(title: 'Goose Eggs')
poultry.children.create(title: 'Quail')
poultry.children.create(title: 'Quail Eggs')
poultry.children.create(title: 'Pigeon')
poultry.children.create(title: 'Pigeon Eggs')